___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [3]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [3]:
print(np.__version__)


1.19.2


Створити вектор з 10 елементів, заповнений одиницями:

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Створити матрицю 5 на 5, заповнену нулями:

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [4]:
Z = np.random.randint(0, 3, 20)
print(Z, "Наш вектор")
print(np.nonzero(Z), 'індексы ненульових значень')




[1 1 0 0 2 1 0 2 1 0 1 1 0 0 2 2 2 2 2 0] Наш вектор
(array([ 0,  1,  4,  5,  7,  8, 10, 11, 14, 15, 16, 17, 18], dtype=int64),) індексы ненульових значень


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [57]:
np.mean(Z) # середнє значення

0.7

In [59]:
np.std(Z) # відхилення

0.714142842854285

In [60]:
np.median(Z) # медіана

1.0

Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [120]:
Z1 = np.random.randint(0, 3, (4, 2))
Z2 = np.random.randint(0, 3, (2, 2))

Z3 = Z1@Z2
Z3

array([[5, 4],
       [2, 4],
       [4, 2],
       [1, 2]])

Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [121]:
vectZ3 = np.ravel(Z3) # перетворюємо у вектор
print(vectZ3.max())  # макимальне 
print(vectZ3.min())  # мінімальне
vectZ3[np.argmax(vectZ3)] = 0 # знаходимо индекс максимального значення і змінюємо його згначення
vectZ3

5
1


array([0, 4, 2, 4, 4, 2, 1, 2])

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [127]:
first = Z3[0] # Беремо перший рядок за нашої матриці

without_first = np.delete(Z3, (0), axis=0) # Робимо матрицю без першого рядка

for i in without_first:                     # Вираховуємо корелляцію першого рядка з іншими
    print(np.correlate(first, i))


[16]
[8]
[8]


Дано матрицю. Знайти ранг матриці:

In [101]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

from numpy import linalg as LA
LA.matrix_rank(a)

3

Знайти визначник матриці:

In [102]:
LA.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [103]:
wb, vb = LA.eigh(a)
print(wb)
print(vb)

[-14.30540864  -4.34740072  23.65280936]
[[ 0.15315575  0.88160309  0.44645191]
 [ 0.63674998 -0.43353159  0.6376518 ]
 [-0.75570681 -0.18661821  0.62775861]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [109]:
a = np.random.randint(0,10,50)
print(a)

from scipy.stats import mode

print(mode(a))

[5 1 0 0 9 3 7 4 8 9 8 6 2 0 7 6 4 9 6 1 3 7 3 9 3 6 9 1 5 4 7 2 6 5 1 9 6
 4 8 7 4 4 9 9 5 7 6 2 3 6]
ModeResult(mode=array([6]), count=array([8]))


Виведіть лише парні числа, що діляться на 5:

In [140]:
a = np.random.randint(0,100,50)
new_a = a[a % 5 == 0 ]
new_a[new_a % 2 == 0]

array([20, 20, 90, 70,  0, 80, 20])

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [141]:
M1 = np.array([[2., 5.], [1., -10.]]) 
v1 = np.array([1., 3.]) 

np.linalg.solve(M1, v1)

array([ 1. , -0.2])